package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"

	"github.com/Hueter57/graphql-go-test/graph/model"
	"github.com/Hueter57/graphql-go-test/internal"
)

// AddProjectV2ItemByID is the resolver for the addProjectV2ItemById field.
func (r *mutationResolver) AddProjectV2ItemByID(ctx context.Context, input model.AddProjectV2ItemByIDInput) (*model.AddProjectV2ItemByIDPayload, error) {
	panic(fmt.Errorf("not implemented: AddProjectV2ItemByID - addProjectV2ItemById"))
}

// Items is the resolver for the items field.
func (r *projectV2Resolver) Items(ctx context.Context, obj *model.ProjectV2, after *string, before *string, first *int, last *int) (*model.ProjectV2ItemConnection, error) {
	panic(fmt.Errorf("not implemented: Items - items"))
}

// Owner is the resolver for the owner field.
func (r *projectV2Resolver) Owner(ctx context.Context, obj *model.ProjectV2) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Owner - owner"))
}

// Node is the resolver for the node field.
func (r *projectV2EdgeResolver) Node(ctx context.Context, obj *model.ProjectV2Edge) (*model.ProjectV2, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// Mutation returns internal.MutationResolver implementation.
func (r *Resolver) Mutation() internal.MutationResolver { return &mutationResolver{r} }

// ProjectV2 returns internal.ProjectV2Resolver implementation.
func (r *Resolver) ProjectV2() internal.ProjectV2Resolver { return &projectV2Resolver{r} }

// ProjectV2Edge returns internal.ProjectV2EdgeResolver implementation.
func (r *Resolver) ProjectV2Edge() internal.ProjectV2EdgeResolver { return &projectV2EdgeResolver{r} }

type mutationResolver struct{ *Resolver }
type projectV2Resolver struct{ *Resolver }
type projectV2EdgeResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *projectV2ConnectionResolver) Edges(ctx context.Context, obj *model.ProjectV2Connection) ([]*model.ProjectV2Edge, error) {
	panic(fmt.Errorf("not implemented: Edges - edges"))
}
func (r *projectV2ConnectionResolver) Nodes(ctx context.Context, obj *model.ProjectV2Connection) ([]*model.ProjectV2, error) {
	panic(fmt.Errorf("not implemented: Nodes - nodes"))
}
func (r *Resolver) ProjectV2Connection() internal.ProjectV2ConnectionResolver {
	return &projectV2ConnectionResolver{r}
}
type projectV2ConnectionResolver struct{ *Resolver }
*/
