package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"

	"github.com/Hueter57/graphql-go-test/graph/model"
	"github.com/Hueter57/graphql-go-test/internal"
)

// Repository is the resolver for the repository field.
func (r *pullRequestResolver) Repository(ctx context.Context, obj *model.PullRequest) (*model.Repository, error) {
	panic(fmt.Errorf("not implemented: Repository - repository"))
}

// ProjectItems is the resolver for the projectItems field.
func (r *pullRequestResolver) ProjectItems(ctx context.Context, obj *model.PullRequest, after *string, before *string, first *int, last *int) (*model.ProjectV2ItemConnection, error) {
	panic(fmt.Errorf("not implemented: ProjectItems - projectItems"))
}

// Edges is the resolver for the edges field.
func (r *pullRequestConnectionResolver) Edges(ctx context.Context, obj *model.PullRequestConnection) ([]*model.PullRequestEdge, error) {
	panic(fmt.Errorf("not implemented: Edges - edges"))
}

// Nodes is the resolver for the nodes field.
func (r *pullRequestConnectionResolver) Nodes(ctx context.Context, obj *model.PullRequestConnection) ([]*model.PullRequest, error) {
	panic(fmt.Errorf("not implemented: Nodes - nodes"))
}

// Node is the resolver for the node field.
func (r *pullRequestEdgeResolver) Node(ctx context.Context, obj *model.PullRequestEdge) (*model.PullRequest, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// PullRequest returns internal.PullRequestResolver implementation.
func (r *Resolver) PullRequest() internal.PullRequestResolver { return &pullRequestResolver{r} }

// PullRequestConnection returns internal.PullRequestConnectionResolver implementation.
func (r *Resolver) PullRequestConnection() internal.PullRequestConnectionResolver {
	return &pullRequestConnectionResolver{r}
}

// PullRequestEdge returns internal.PullRequestEdgeResolver implementation.
func (r *Resolver) PullRequestEdge() internal.PullRequestEdgeResolver {
	return &pullRequestEdgeResolver{r}
}

type pullRequestResolver struct{ *Resolver }
type pullRequestConnectionResolver struct{ *Resolver }
type pullRequestEdgeResolver struct{ *Resolver }
