package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"

	"github.com/Hueter57/graphql-go-test/graph/model"
	"github.com/Hueter57/graphql-go-test/internal"
)

// Repository is the resolver for the repository field.
func (r *pullRequestResolver) Repository(ctx context.Context, obj *model.PullRequest) (*model.Repository, error) {
	panic(fmt.Errorf("not implemented: Repository - repository"))
}

// ProjectItems is the resolver for the projectItems field.
func (r *pullRequestResolver) ProjectItems(ctx context.Context, obj *model.PullRequest, after *string, before *string, first *int, last *int) (*model.ProjectV2ItemConnection, error) {
	panic(fmt.Errorf("not implemented: ProjectItems - projectItems"))
}

// Node is the resolver for the node field.
func (r *pullRequestEdgeResolver) Node(ctx context.Context, obj *model.PullRequestEdge) (*model.PullRequest, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// PullRequest returns internal.PullRequestResolver implementation.
func (r *Resolver) PullRequest() internal.PullRequestResolver { return &pullRequestResolver{r} }

// PullRequestEdge returns internal.PullRequestEdgeResolver implementation.
func (r *Resolver) PullRequestEdge() internal.PullRequestEdgeResolver {
	return &pullRequestEdgeResolver{r}
}

type pullRequestResolver struct{ *Resolver }
type pullRequestEdgeResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *pullRequestConnectionResolver) Edges(ctx context.Context, obj *model.PullRequestConnection) ([]*model.PullRequestEdge, error) {
	panic(fmt.Errorf("not implemented: Edges - edges"))
}
func (r *pullRequestConnectionResolver) Nodes(ctx context.Context, obj *model.PullRequestConnection) ([]*model.PullRequest, error) {
	panic(fmt.Errorf("not implemented: Nodes - nodes"))
}
func (r *Resolver) PullRequestConnection() internal.PullRequestConnectionResolver {
	return &pullRequestConnectionResolver{r}
}
type pullRequestConnectionResolver struct{ *Resolver }
*/
